version: '3.9'

services:
  server:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    env_file:
      - .env
    environment:
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - SECRET_KEY
      - DEBUG
      - ALLOWED_HOSTS
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:13-alpine
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - server
    ports:
      - 8080:8000
    volumes:
      - static-data:/vol/static
  
volumes:
  postgres-data:
  static-data: